### PR TITLE
First take at implementing ps command (closes #14)

### LINKED ISSUE #14: Implement ps command
Examples:

```
$ harbor-compose ps

SHIPMENT      mss-poc-multi-container   
ENVIRONMENT   dev                       
STATUS        Running                   
CONTAINERS    2                         
REPLICAS      2

IMAGE                                                        STARTED      STATUS    RESTARTS   
registry.services.dmtio.net/mss-poc-multi-container:1.0.0    5 days ago   running   1          
registry.services.dmtio.net/mss-poc-multi-container2:1.0.0   5 days ago   running   1          
registry.services.dmtio.net/mss-poc-multi-container:1.0.0    1 day ago    running   2          
registry.services.dmtio.net/mss-poc-multi-container2:1.0.0   1 day ago    running   2 
```

```
SHIPMENT:      mss-poc-thingproxy2   
ENVIRONMENT:   dev                   
STATUS:        Running               
CONTAINERS:    1                     
REPLICAS:      2

IMAGE                                                         STATUS    STARTED            RESTARTS   LAST STATE                 
registry.services.dmtio.net/mss-poc-thingproxy:0.0.13-rc.33   waiting   CrashLoopBackOff   17         terminated 2 minutes ago   
registry.services.dmtio.net/mss-poc-thingproxy:0.0.13-rc.33   waiting   CrashLoopBackOff   17         terminated 5 minutes ago  
```

### PR DESCRIPTION
**Pull request by jritsema**
Example output...

```
$ harbor-compose generate mss-poc-multi-container dev
done

$harbor-compose ps

SHIPMENT      mss-poc-multi-container   
ENVIRONMENT   dev                       
STATUS        Running                   
CONTAINERS    2                         
REPLICAS      2

IMAGE                                                        STARTED      STATUS    RESTARTS   
registry.services.dmtio.net/mss-poc-multi-container:1.0.0    5 days ago   running   1          
registry.services.dmtio.net/mss-poc-multi-container2:1.0.0   5 days ago   running   1          
registry.services.dmtio.net/mss-poc-multi-container:1.0.0    1 day ago    running   2          
registry.services.dmtio.net/mss-poc-multi-container2:1.0.0   1 day ago    running   2 
```

### CODE REVIEW

**Review by jkurz — APPROVED** [review]
Looks awesome.

**Comment by jritsema** [comment]
I need to have a look at the other Harbor API.  It would be nice if we could get/display the container IDs so that they could be used in conjunction with the `logs` command to drill into a particular container instance.

File: cmd/helmitTypes.go [hunk 1]
```diff
@@ -21,3 +23,26 @@ type HelmitResponse struct {
...
+	Namespace string `json:"namespace"`
+	Version   string `json:"version"`
+	Status    struct {
+		Phase      string `json:"phase"`
+		Containers []struct {
+			Image    string `json:"image"`
+			Ready    bool   `json:"ready"`
+			Restarts int    `json:"restarts"`
+			State    struct {
+				Running struct {
```
Comment (wilsonodk) [inline cmd/helmitTypes.go]: State may not alway be `Running`. It could be `Waiting`. For example, you may get:

``` json
"state": {
  "waiting": {
    "reason": "CrashLoopBackOff",
    "message": "Back-off 5m0s restarting failed container=cnn-now pod=thedeployment-3494639297-303ad_cnn-now-prod(94291f44-6fa4-11e6-ae33-0a72129afe9b)"
  }
}
```

Don't know if that matters or not here.

Comment (jritsema) [reply cmd/helmitTypes.go]: Excellent point.  I thought I tested a non-Running state, but perhaps not.

Comment (jritsema) [inline cmd/helmitTypes.go]: Ok, I did look at the other API, however, it didn't have the `"startedAt"` field which I thought would be useful.  It also includes logs which could potentially be a lot of data to return.

**Comment by jritsema** [comment]
Ok, I did look at the other API, however, it didn't have the "startedAt" field which I thought would be useful. It also includes logs which could potentially be a lot of data to return.

File: cmd/helmitTypes.go (hunk 1 above)
Comment (jritsema) [reply cmd/helmitTypes.go]: Ok, I added support for unhealthy states (example below).  I'm hoping `CrashLoopBackOff` along with the `LAST STATE` field helps tell the story of what's happening to a container.  Also provides some context for the `RESTARTS` field.  Let me know what you think.  Also are there any other states that we should be accounting for?

```
SHIPMENT:      mss-poc-thingproxy2   
ENVIRONMENT:   dev                   
STATUS:        Running               
CONTAINERS:    1                     
REPLICAS:      2

IMAGE                                                         STATUS    STARTED            RESTARTS   LAST STATE                 
registry.services.dmtio.net/mss-poc-thingproxy:0.0.13-rc.33   waiting   CrashLoopBackOff   17         terminated 2 minutes ago   
registry.services.dmtio.net/mss-poc-thingproxy:0.0.13-rc.33   waiting   CrashLoopBackOff   17         terminated 5 minutes ago  
```

**Comment by jritsema** [comment]
Added container ID (thanks @wilsonodk).  Let me know if you have any more feedback before I merge this.

**Review by wilsonodk — APPROVED** [review]
